version: '3'

services:
  tgstate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${port}:8088"
    env_file:
      - config.env
    restart: unless-stopped
    volumes:
      - ./data:/app/data