version: '3'

services:
  tgstate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${port}:8088"
    environment:
      - token=${token}
      - target=${target}
      - mode=${mode}
      - port=${port}
    env_file:
      - ./config.env
    restart: always
    volumes:
      - ./data:/app/data