version: '3'

services:
  tgstate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${port}:8088"
    environment:
      - token=${token}
      - target=${target}
      - mode=${mode}
      - port=${port}
    # 移除 env_file 配置，因为我们已经使用 .env 文件
    # env_file:
    #   - ./config.env
    restart: always
    volumes:
      - ./data:/app/data